### ISSUE TITLE
branch.subscribe listener not registered when opening the app first time

### ISSUE THREAD

**Issue by dwaligora** [BranchMetrics/react-native-branch-deep-linking#322]
Hi Guys,

I have serious problem with making the android branch.io working.

I have checked the issues list and looks like it was reported several times in the past but without exact solution. Let me describe my problem.

In the `componentDidMount` method in my top level app container I am registering the branch.io `subscribe` listener.

```javascript
  async componentDidMount() {
    branch.subscribe(async ({ params, error }) => {
      // ... body
    }
```

Like I said this is top level container of my app that includes `react-navigation` and all initial, basic setup:

```javascript
 renderContent = () => {
    const { authProfileData, childrenData, drawerIsOpen, navigation, isBootstrapped } = this.props

    if (isBootstrapped) {
      return (
        <DrawerMenu
          close={this.props.closeDrawer}
          isOpen={drawerIsOpen}
          items={childrenData}
          loggedUser={authProfileData}
          onLogoutButtonPress={this.handleLogout}
          onItemPress={this.handleDrawerItemPress}
        >
          <AppNavigator
            navigation={addNavigationHelpers({
              dispatch: this.props.dispatch,
              state: navigation,
            })}
          />
        </DrawerMenu>
      )
    }

    return <SplashScreen />
  }

  render() {
    return this.renderContent()
  }
```

At this point, everything works perfect on the iOS (dev and prod) and android (dev) but unfortunatelly, when I download the app from the google play, install, open and click link from the email, nothing happens, the event listener is not registered and it is not capturing the incoming branch.io deep link.

When I close the app, open again and do the same...everything works perfect! 

Like you can see that happens *only* when I open the app first time, in prod mode, directly from the google play download.

I have tried setting timout, re-registering event listener in the didUpdate methods, but nothing seems working. 

I will be extremely thankful for any help because I stuck a bit with that. Thanks in advance!

**Comment by dwaligora** [comment]
any help guys? I really stuck with that. I am happy to provide more information if anyone is willing to help me with that.

**Comment by sequoiaat** [comment]
Hi

We believe the following as  the issue:
  - Branch.subscribe uses a timeout value (initSessionTtl), which has a default value of 5 seconds.
  - The parameters the app was launched with is returned only if branch.subscribe is called within this timeout.
  - Otherwise, it just adds event handler to DeviceEventEmitter.
  - 'componentDidMount' is called after the component is loaded. The delay for this is usually within 5 seconds.
  - But usually loading app and rendering takes more time on first launch after installation.
  - This is why branch.subscribe callback is not called with the parameters.

Option 1  (Please follow the branch example exactly):
  - Call branch.subscribe as global (outside react component), instead of calling on 'componentDidMount'.
  - Refer example in the GitHub repository: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/testbed_native_android/src/Subscribe.js

Option 2 (Workaround by increasing timeout):
  - Increase the session init timeout.
      branch.initSessionTtl = 10000; // 10 seconds
      branch.subscribe(({ error, params }) => {
      ......

Meanwhile we are working on a permanent fix for this to support both cases (global call and async).

**Comment by sequoiaat** [comment]
Hi,

We have committed a permanent  fix for this which should get published  soon.

**Comment by hqaisrani-apigarage** [comment]
@sequoiaat Was the permanent fix published?

**Comment by csalmi-branch** [comment]
@hqaisrani-apigarage The fix for this issue was released in v2.5.5
https://github.com/BranchMetrics/react-native-branch-deep-linking/releases/tag/v2.2.5

Are you experiencing the problem again? If so, can you open up a new github issue, or submit a ticket to our support team?

**Comment by Seamus1989** [comment]
still an issue

**Comment by crazycoder-io** [comment]
I still have the similar issue in 2023!!

Versions
React Native: 0.68.6
React: 17.0.2
React Native Branch: 5.8.0

The issue is happening only on IOS, I have done about all `branch.json` file.
The issue is when I open the app from scratch the `subscribe` function gets invoked if there is **no** deeplink pressed/used but if while the app closed and pressed a deeplink the `subscribe` function does not get invoke. I sent the app background and press the deeplink and it does invoke the `subscribe` function. 

Tested on iPhone 14 Pro Max simulator
Test on iPhone 7

Can anybody help me?

**Comment by crazycoder-io** [comment]
🥳🥳 RESOLVED 🥳🥳

My issue was all IOS. And it was not invoking the `branch.subscribe` function while I open the app with deeplink although when I open the app normally (withOUT the deeplink) it was running `branch.subscribe`.

It was strange and this is what they explain on their release doc for 5.8.0;

https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases/tag/v5.8.0

And it was already implemented on our system however it was not working for IOS and I removed it from IOS and has immediately started to work. So I keep `branch.json` for android and removed from IOS.

If this happens for you keep in your mind and remove `branch.json` for IOS.
