### ISSUE TITLE
Branch is messing up push notifications click events on android

### ISSUE THREAD

**Issue by Hitabis** [BranchMetrics/react-native-branch-deep-linking#99]
We are using "React Native Push Notifications"
https://github.com/zo0r/react-native-push-notification

When we started using branch.io it stopped working for android.

1. App is in background 

- we receive a notifcation 
- we click on the notification
- onNotification is **not** triggered for react-native-push-notification
- but when we reload the app (in development) onNotification event is triggered

2. App is foreground everything works

3. App is closed everything works, even clicking the notification

When we turn off branch.io everything is fine again.

**Comment by jdee** [comment]
Thanks for the error report, @Hitabis. I haven't worked with react-native-push-notification before, but I set up a sample app to try and confirm this bug. I spent some time reviewing how that module works. I don't see any obvious reason onNotification would not be called or how Branch could interfere. I'm still working on testing, but I had a couple of questions:

1. Does everything work properly on iOS? You only mentioned Android.
2. Does this problem happen with local notifications or only remote notifications? I ask because it's more involved to set up remote notifications in a test app. If you get the same behavior with local notifications, I can work with that instead. 

I'll keep you posted. Sorry for the trouble.

**Comment by Hitabis** [comment]
Hi @jdee,

thank you very much for your efforts.


We only have this issue on android and we are using remote notifications. We nailed it down to the intent. When we remove these lines 
```
    @Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }
```
it works again.

We will test it with local notifications as soon as possible and get back.

**Comment by Hitabis** [comment]
Hey @jdee,

we fixed it a little. When adding a super
```
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        this.setIntent(intent);
    }
```

**onNotification** is triggered. But will be also trigged after each reload (in dev mode). This is no issue in production. So we could live with it. We hope no other issue will result from that.

**Comment by jdee** [comment]
@Hitabis Thanks for the update. It looks like it's the call to setIntent that is at fault and that links and push notifications share this code path. I wonder if you can distinguish the two and only call setIntent when a link intent is received, maybe using the action or the component:

```Java
@Override
public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    // for push notifications, action should be com.google.android.c2dm.intent.RECEIVE
    // for links, android.intent.action.VIEW
    if (intent.getAction().matches("RECEIVE")) return;
    setIntent(intent);
}
```

**Comment by Nathan187** [comment]
Recently stumbled on to this for we are having a similar issue.  We are using Angular / Ionic / Capacitor and we cannot receive push notifications when the app is closed or in the background.  It was suggest that branch.io may have something to do with it

I used the code snippet from jdee, however we are still having this issue.  Any help / remarks would be helpful indeed

**Comment by jf-branch** [comment]
Hey @Nathan187 , I would suggest to create a ticket so that our support team can help you further https://help.branch.io/using-branch/page/submit-a-ticket
